apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  rules:
    - host: {{ .Values.service.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.service.name }}
              servicePort: {{ .Values.service.internalPort }}
